version: "4"
services:
### AI VECTOR DB
  pgvector:
    image: pgvector/pgvector:pg16
    ports:
      - '5440:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_UN}
      POSTGRES_PASSWORD: ${DB_PWD}
    labels:
      - "org.springframework.boot.service-connection=postgres"